/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 疎通確認 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["pong"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** wikiページの作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["newPage"];
                };
            };
            responses: {
                /** @description Created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["page"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{pageID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** wikiページの取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageID: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["page"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** wikiページの削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageID: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** wikiページの更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageID: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["patchPage"];
                };
            };
            responses: {
                /** @description Updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["page"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/pages/{pageID}/child": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** wikiページの子ページ取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pageID: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["pageAbstract"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        pong: {
            /** @example pong */
            message: string;
        };
        page: {
            /** @example 1 */
            id: number;
            /** @example /path/to/page */
            path: string;
            /** @example page */
            name: string;
            /** @example title */
            title: string;
            /** @example wikiページの内容 */
            body: string;
            /**
             * Format: date-time
             * @example 2021-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2021-01-01T00:00:00Z
             */
            updated_at: string;
            /** @example owner */
            creator: string;
        };
        newPage: {
            /** @example 1 */
            parentID: number;
            /** @example page */
            name: string;
            /** @example title */
            title: string;
            /** @example wikiページの内容 */
            body: string;
            /** @example owner */
            creator: string;
        };
        patchPage: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            parentID: number;
            /** @example page */
            name: string;
            /** @example title */
            title: string;
            /** @example wikiページの内容 */
            body: string;
            /** @example owner */
            creator: string;
        };
        pageAbstract: {
            /** @example 1 */
            id: number;
            /** @example /path/to/page */
            path: string;
            /** @example title */
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
