openapi: 3.0.3
info:
  title: writedown
  description: writedown
  version: 1.0.0
tags:
  - name: ping
    description: 疎通確認
  - name: pages
    description: wikiページ
  - name: users
    description: ユーザー
  - name: tags
    description: ページのタグ
  - name: login
    description: ログイン
paths:
  /ping:
    get:
      tags:
        - ping
      summary: 疎通確認
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pong'
  /pages:
    $ref: './paths/pages/pages.yaml'
  /pages/{pageID}:
    $ref: './paths/pages/pages_id.yaml'
  /pages/{pageID}/child:
    $ref: './paths/pages/pages_child.yaml'
  /pages/{pageID}/tag:
    $ref: './paths/pages/pages_tag.yaml'
  /pages/tag:
    $ref: './paths/pages/tag.yaml'
  /users/signup:
    $ref: './paths/users/signup.yaml'
  /users/login:
    $ref: './paths/users/login.yaml'
  /users/me:
    $ref: './paths/users/me.yaml'

components:
  schemas:
    pong:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: pong