version: '3.8'

services:
  writedown:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_NAME: writedown
    depends_on:
      mariadb:
        condition: service_healthy
  
  mariadb:
    image: mariadb:10.11.9
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: writedown
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      interval: 1s
      timeout: 10s
      retries: 60
  
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DEFAULT_USERNAME: root
      ADMINER_DEFAULT_PASSWORD: password
    depends_on:
      - mariadb