openapi: 3.0.3
info:
  title: writedown
  description: writedown
  version: 1.0.0
tags:
  - name: ping
    description: 疎通確認
  - name: pages
    description: wikiページ
paths:
  /ping:
    get:
      tags:
        - ping
      summary: 疎通確認
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pong'
  /pages:
    post:
      tags:
        - pages
      summary: wikiページの作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newPage'
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/page'
  /pages/{pageID}:
    get:
      tags:
        - pages
      summary: wikiページの取得
      parameters:
        - name: pageID
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/page'
    patch:
      tags:
        - pages
      summary: wikiページの更新
      parameters:
        - name: pageID
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/patchPage'
      responses:
        '200':
          description: Updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/page'
    delete:
      tags:
        - pages
      summary: wikiページの削除
      parameters:
        - name: pageID
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '204':
          description: Deleted successfully
  /pages/{pageID}/child:
    get:
      tags:
        - pages
      summary: wikiページの子ページ取得
      parameters:
        - name: pageID
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pageAbstract'
components:
  schemas:
    pong:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: pong
    page:
      type: object
      required:
        - id
        - path
        - title
        - body
        - created_at
        - updated_at
        - creator
      properties:
        id:
          type: integer
          format: int64
          example: 1
        path:
          type: string
          example: /path/to/page
        title:
          type: string
          example: title
        body:
          type: string
          example: wikiページの内容
        created_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
        creator:
          type: string
          example: owner
    newPage:
      type: object
      required:
        - parentID
        - title
        - body
        - creator
      properties:
        parentID:
          type: integer
          example: 1
        title:
          type: string
          example: title
        body:
          type: string
          example: wikiページの内容
        creator:
          type: string
          example: owner
    patchPage:
      type: object
      required:
        - id
        - parentID
        - title
        - body
        - creator
      properties:
        id:
          type: integer
          example: 1
        parentID:
          type: integer
          example: 1
        title:
          type: string
          example: title
        body:
          type: string
          example: wikiページの内容
        creator:
          type: string
          example: owner
    pageAbstract:
      type: object
      required:
        - id
        - path
        - title
      properties:
        id:
          type: integer
          example: 1
        path:
          type: string
          example: /path/to/page
        title:
          type: string
          example: title
