// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openapi

// Pong defines model for pong.
type Pong struct {
	Message *string `json:"message,omitempty"`
}
