// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openapi

import (
	"time"
)

// NewPage defines model for newPage.
type NewPage struct {
	Body    *string `json:"body,omitempty"`
	Creator *string `json:"creator,omitempty"`
	Path    *string `json:"path,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// Page defines model for page.
type Page struct {
	Body      *string    `json:"body,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Creator   *string    `json:"creator,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Path      *string    `json:"path,omitempty"`
	Title     *string    `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PageAbstract defines model for pageAbstract.
type PageAbstract struct {
	Id    *int    `json:"id,omitempty"`
	Path  *string `json:"path,omitempty"`
	Title *string `json:"title,omitempty"`
}

// PatchPage defines model for patchPage.
type PatchPage struct {
	Body    *string `json:"body,omitempty"`
	Creator *string `json:"creator,omitempty"`
	Id      *int    `json:"id,omitempty"`
	Path    *string `json:"path,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// Pong defines model for pong.
type Pong struct {
	Message *string `json:"message,omitempty"`
}

// PostPagesJSONRequestBody defines body for PostPages for application/json ContentType.
type PostPagesJSONRequestBody = NewPage

// PatchPagesPageIDJSONRequestBody defines body for PatchPagesPageID for application/json ContentType.
type PatchPagesPageIDJSONRequestBody = PatchPage
