// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openapi

import (
	"time"
)

// NewPage defines model for newPage.
type NewPage struct {
	Body     string `json:"body"`
	Creator  string `json:"creator"`
	Name     string `json:"name"`
	ParentID int    `json:"parentID"`
	Title    string `json:"title"`
}

// Page defines model for page.
type Page struct {
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	Creator   string    `json:"creator"`
	Id        int       `json:"id"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// PageAbstract defines model for pageAbstract.
type PageAbstract struct {
	Id    int    `json:"id"`
	Path  string `json:"path"`
	Title string `json:"title"`
}

// PatchPage defines model for patchPage.
type PatchPage struct {
	Body     string `json:"body"`
	Creator  string `json:"creator"`
	Id       int    `json:"id"`
	Name     string `json:"name"`
	ParentID int    `json:"parentID"`
	Title    string `json:"title"`
}

// Pong defines model for pong.
type Pong struct {
	Message string `json:"message"`
}

// PostPagesJSONRequestBody defines body for PostPages for application/json ContentType.
type PostPagesJSONRequestBody = NewPage

// PatchPagesPageIDJSONRequestBody defines body for PatchPagesPageID for application/json ContentType.
type PatchPagesPageIDJSONRequestBody = PatchPage
