# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: openapi
output: server.gen.go
generate:
  echo-server: true
output-options:
  skip-prune: true
  nullable-type: true